version: '3.9'

services:
  server:
    build: ./server
    container_name: manamartServer
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env.docker
    volumes:
      - ./server:/app
      - /app/node_modules
    command: >
      sh -c "
        sleep 5 &&
        node scripts/import.js &&
        npm start
      "

  frontend:
    build: ./frontend
    container_name: manamartFrontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
